name: play_games
description: A simple wrapper on top of Google Play Games Services (GPGS), including auth, achievement, and more.
version: 0.1.0
author: Luan Nico <luannico27@gmail.com>
homepage: https://github.com/luanpotter/play_games

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: xyz.luan.games.play.playgames
    pluginClass: PlayGamesPlugin
